### ISSUE TITLE
Plot2dynmap fault after upgrade to 2.5.6

### ISSUE THREAD

**Issue by EvilOlaf** [IntellectualCrafters/PlotSquared#89]
```
[20:11:05] [Server thread/WARN]: [Plot2Dynmap] Task #44 for Plot2Dynmap v1.0.4 generated an exception
java.lang.NoSuchMethodError: com.intellectualcrafters.plot.object.PlotSettings.getFlags()Ljava/util/Set;
	at com.empcraft.plot2dynmap.Main.updatePlots(Main.java:271) ~[?:?]
	at com.empcraft.plot2dynmap.Main.access$1(Main.java:203) ~[?:?]
	at com.empcraft.plot2dynmap.Main$Plot2Update.run(Main.java:104) ~[?:?]
	at org.bukkit.craftbukkit.v1_8_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[craftbukkit.jar:git-Spigot-eb39b47-0899683]
	at org.bukkit.craftbukkit.v1_8_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [craftbukkit.jar:git-Spigot-eb39b47-0899683]
	at net.minecraft.server.v1_8_R1.MinecraftServer.z(MinecraftServer.java:694) [craftbukkit.jar:git-Spigot-eb39b47-0899683]
	at net.minecraft.server.v1_8_R1.DedicatedServer.z(DedicatedServer.java:316) [craftbukkit.jar:git-Spigot-eb39b47-0899683]
	at net.minecraft.server.v1_8_R1.MinecraftServer.y(MinecraftServer.java:623) [craftbukkit.jar:git-Spigot-eb39b47-0899683]
	at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:526) [craftbukkit.jar:git-Spigot-eb39b47-0899683]
	at java.lang.Thread.run(Unknown Source) [?:1.7.0_65]
```

Worked well with PlotSquared 2.5.3

Spigot 1.8

**Comment by boy0001** [comment]
kk, I'll update it.

**Comment by boy0001** [comment]
Done.

**Comment by EvilOlaf** [comment]
As expected, thanks.
